apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer-service
  labels:
    app: prod
spec:
  type: LoadBalancer # Service Type
  selector:
    app: prod # Label to select
  ports:
    - protocol: TCP
      port: 2000 # Service Port
      targetPort: 80 # Pode Port
      nodePort: 32000 # Node Port